### ISSUE TITLE
Fix feed that breaks UI

### ISSUE THREAD

**Issue by mariocao** [witnet/data-feed-app#45]
This [feed](https://feeds.witnet.io/feeds/60f2ad37f592ee573a7eb713) is breaking the explorer. Check why and fix! :)

**Comment by Tommytrg** [comment]
I have found an entry in the database which contains `null` values:
```
{ "_id" : ObjectId("6100082f69c164c5dcd865e6"), "feedId" : "60f2ad37f592ee573a7eb713", "result" : null, "timestamp" : null, "requestId" : null, "address" : "0xAa0AA725aEb1d382F909a8dE3041e9eaD6507501", "drTxHash" : null, "label" : "$" 
```
I have remove it to avoid this error but I will also improve the validation of the elements before inserting them in the database
