### ISSUE TITLE
Goerli feeds are broken

### ISSUE THREAD

**Issue by aesedepece** [witnet/data-feed-app#57]
- https://feeds.witnet.io/feeds/60f2ad37f592eea6487eb712
- https://feeds.witnet.io/feeds/60f2ad37f592ee573a7eb713

**Comment by aesedepece** [comment]
Did you notice? @tommytrg

**Comment by Tommytrg** [comment]
Once #59 is deployed `null`values can't be added into de database

**Comment by Tommytrg** [comment]
Let's keep this open until de deploy the #59 and we ensure feeds aren't broken

**Comment by Tommytrg** [comment]
#59 is closed and there aren't more null values
